[package]
name = "crabking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reedline = "0.32.0"
regex = "1.10.4"
reqwest = "0.12.4"
tokio = {version= "1.37.0", features = ["full"]}
